title: Introduction to New Media | CPLS UN3770
description: >
  Spring 2017 | Tue/Thu 1:10-2:25 | Location TBD
baseurl: "/digitalmedia"
url: "https://gwijthoff.github.io/digitalmedia/"
paginate:	1 # The number of posts to show per page on your homepage
name: "Grant Wythoff"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate