title: Immaculate
description: >
  A beautiful, fast, AMP-compliant Jekyll theme based on Tufte CSS.
baseurl: "/digitalmedia"
url: "https://gwijthoff.github.io/digitalmedia/"
paginate:	2 # The number of posts to show per page on your homepage
name: "Lau Siaw Young"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
